# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: department/department.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
require 'common/messages_pb'


descriptor_data = "\n\x1b\x64\x65partment/department.proto\x12!bannote.userservice.department.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x15\x63ommon/messages.proto\"\x84\x01\n\nDepartment\x12\'\n\x0f\x64\x65partment_code\x18\x01 \x01(\tR\x0e\x64\x65partmentCode\x12\x12\n\x04name\x18\x02 \x01(\tR\x04name\x12\x39\n\ncreated_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\tcreatedAt\"\xad\x01\n\x13\x44\x65partmentWithAudit\x12M\n\ndepartment\x18\x01 \x01(\x0b\x32-.bannote.userservice.department.v1.DepartmentR\ndepartment\x12G\n\naudit_info\x18\x02 \x01(\x0b\x32(.bannote.userservice.common.v1.AuditInfoR\tauditInfoB\xa6\x02\n%com.bannote.userservice.department.v1B\x0f\x44\x65partmentProtoP\x01ZEgithub.com/kyumin1227/bannote-proto/gen/go/user-service/department/v1\xa2\x02\x03\x42UD\xaa\x02!Bannote.Userservice.Department.V1\xca\x02!Bannote\\Userservice\\Department\\V1\xe2\x02-Bannote\\Userservice\\Department\\V1\\GPBMetadata\xea\x02$Bannote::Userservice::Department::V1b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Bannote
  module Userservice
    module Department
      module V1
        Department = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bannote.userservice.department.v1.Department").msgclass
        DepartmentWithAudit = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bannote.userservice.department.v1.DepartmentWithAudit").msgclass
      end
    end
  end
end
