# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: department/service.proto for package 'Bannote.Userservice.Department.V1'

require 'grpc'
require 'department/service_pb'

module Bannote
  module Userservice
    module Department
      module V1
        module DepartmentService
          # The department service definition.
          class Service

            include ::GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = 'bannote.userservice.department.v1.DepartmentService'

            #  학과 ID로 학과 조회 API
            rpc :GetDepartment, ::Bannote::Userservice::Department::V1::GetDepartmentRequest, ::Bannote::Userservice::Department::V1::GetDepartmentResponse
            #  학과 생성 API
            rpc :CreateDepartment, ::Bannote::Userservice::Department::V1::CreateDepartmentRequest, ::Bannote::Userservice::Department::V1::CreateDepartmentResponse
            #  학과 수정 API
            rpc :UpdateDepartment, ::Bannote::Userservice::Department::V1::UpdateDepartmentRequest, ::Bannote::Userservice::Department::V1::UpdateDepartmentResponse
            #  학과 삭제 API
            rpc :DeleteDepartment, ::Bannote::Userservice::Department::V1::DeleteDepartmentRequest, ::Bannote::Userservice::Department::V1::DeleteDepartmentResponse
            #  학과 목록 조회 API
            rpc :ListDepartments, ::Bannote::Userservice::Department::V1::ListDepartmentsRequest, ::Bannote::Userservice::Department::V1::ListDepartmentsResponse
          end

          Stub = Service.rpc_stub_class
        end
      end
    end
  end
end
