# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: role/role.proto

require 'google/protobuf'

require 'common/enums_pb'


descriptor_data = "\n\x0frole/role.proto\x12\x1b\x62\x61nnote.userservice.role.v1\x1a\x12\x63ommon/enums.proto\"k\n\x0fUserRoleMapping\x12\x1b\n\tuser_code\x18\x01 \x01(\tR\x08userCode\x12;\n\x04role\x18\x02 \x01(\x0e\x32\'.bannote.userservice.common.v1.UserRoleR\x04roleB\xfc\x01\n\x1f\x63om.bannote.userservice.role.v1B\tRoleProtoP\x01Z?github.com/kyumin1227/bannote-proto/gen/go/user-service/role/v1\xa2\x02\x03\x42UR\xaa\x02\x1b\x42\x61nnote.Userservice.Role.V1\xca\x02\x1b\x42\x61nnote\\Userservice\\Role\\V1\xe2\x02\'Bannote\\Userservice\\Role\\V1\\GPBMetadata\xea\x02\x1e\x42\x61nnote::Userservice::Role::V1b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Bannote
  module Userservice
    module Role
      module V1
        UserRoleMapping = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bannote.userservice.role.v1.UserRoleMapping").msgclass
      end
    end
  end
end
