
services:
  db:
    image: mysql:8.0
    container_name: studyroom_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: studyroom_development
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234

    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: studyroom_app
    command: tail -f /dev/null
    volumes:
      - .:/studyroom_service
      - /studyroom_service/tmp
    working_dir: /studyroom_service
    ports:
      - "3000:3000"
      - "50051:50051"
    depends_on:
      - db
      - redis
      - kafka
    environment:
      RAILS_ENV: development
      DB_HOST: db
      DB_USERNAME: root
      DB_PASSWORD: 1234
      RAILS_MASTER_KEY: de840449ba36702434883c58f5574809
      BUNDLE_DEPLOYMENT: 0
    restart: always

  redis:
    image: redis:7
    container_name: studyroom_redis
    restart: always
    ports:
      - "6379:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: studyroom_zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: studyroom_kafka
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  mysql_data:
