version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: studyroom_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    command: ["mysqld"]
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
