# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

require 'google/protobuf'


descriptor_data = "\n\x0c\x63ommon.proto\x12!bannote.scheduleservice.common.v1\"\x07\n\x05\x45mptyB\xab\x02\n%com.bannote.scheduleservice.common.v1B\x0b\x43ommonProtoP\x01ZNgithub.com/kyumin1227/bannote-proto/gen/go/schedule_service/common/v1;commonv1\xa2\x02\x03\x42SC\xaa\x02!Bannote.Scheduleservice.Common.V1\xca\x02!Bannote\\Scheduleservice\\Common\\V1\xe2\x02-Bannote\\Scheduleservice\\Common\\V1\\GPBMetadata\xea\x02$Bannote::Scheduleservice::Common::V1b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Bannote
  module Scheduleservice
    module Common
      module V1
        Empty = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bannote.scheduleservice.common.v1.Empty").msgclass
      end
    end
  end
end
