# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: user/service.proto for package 'Bannote.Userservice.User.V1'

require 'grpc'
require 'user/service_pb'

module Bannote
  module Userservice
    module User
      module V1
        module UserService
          # The user service definition.
          class Service

            include ::GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = 'bannote.userservice.user.v1.UserService'

            #  이메일로 로그인 요청 API
            rpc :UserLogin, ::Bannote::Userservice::User::V1::UserLoginRequest, ::Bannote::Userservice::User::V1::UserLoginResponse
            #  회원 가입 API (성공 시 프론트에서 로그인 요청)
            rpc :CreateUser, ::Bannote::Userservice::User::V1::CreateUserRequest, ::Bannote::Userservice::User::V1::CreateUserResponse
            #  본인이 스스로 변경 가능한 정보를 변경하는 API
            rpc :UpdateUser, ::Bannote::Userservice::User::V1::UpdateUserRequest, ::Bannote::Userservice::User::V1::UpdateUserResponse
            #  이름으로 유저 검색 API (부분 일치)
            rpc :SearchUsersByName, ::Bannote::Userservice::User::V1::SearchUsersByNameRequest, ::Bannote::Userservice::User::V1::SearchUsersByNameResponse
            #  유저 목록 조회 API (다양한 필터 지원)
            rpc :ListUsers, ::Bannote::Userservice::User::V1::ListUsersRequest, ::Bannote::Userservice::User::V1::ListUsersResponse
          end

          Stub = Service.rpc_stub_class
        end
      end
    end
  end
end
