# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: user/user_group_service.proto for package 'Bannote.Scheduleservice.User.V1'

require 'grpc'
require 'user/user_group_service_pb'

module Bannote
  module Scheduleservice
    module User
      module V1
        module UserGroupService
          class Service

            include ::GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = 'bannote.scheduleservice.user.v1.UserGroupService'

            rpc :AddUserToGroup, ::Bannote::Scheduleservice::User::V1::AddUserToGroupRequest, ::Bannote::Scheduleservice::User::V1::AddUserToGroupResponse
            rpc :GetUsersInGroup, ::Bannote::Scheduleservice::User::V1::GetUsersInGroupRequest, ::Bannote::Scheduleservice::User::V1::GetUsersInGroupResponse
            rpc :RemoveUserFromGroup, ::Bannote::Scheduleservice::User::V1::RemoveUserFromGroupRequest, ::Bannote::Scheduleservice::User::V1::RemoveUserFromGroupResponse
            rpc :GetGroupsOfUser, ::Bannote::Scheduleservice::User::V1::GetGroupsOfUserRequest, ::Bannote::Scheduleservice::User::V1::GetGroupsOfUserResponse
          end

          Stub = Service.rpc_stub_class
        end
      end
    end
  end
end
