# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user/user_group.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'


descriptor_data = "\n\x15user/user_group.proto\x12\x1f\x62\x61nnote.scheduleservice.user.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"z\n\tUserGroup\x12\x17\n\x07user_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n\x08group_id\x18\x02 \x01(\x03R\x07groupId\x12\x39\n\ncreated_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\tcreatedAt\"Y\n\x15UserGroupListResponse\x12@\n\x05users\x18\x01 \x03(\x0b\x32*.bannote.scheduleservice.user.v1.UserGroupR\x05usersB\xd4\x01\n#com.bannote.scheduleservice.user.v1B\x0eUserGroupProtoP\x01\xa2\x02\x03\x42SU\xaa\x02\x1f\x42\x61nnote.Scheduleservice.User.V1\xca\x02\x1f\x42\x61nnote\\Scheduleservice\\User\\V1\xe2\x02+Bannote\\Scheduleservice\\User\\V1\\GPBMetadata\xea\x02\"Bannote::Scheduleservice::User::V1b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Bannote
  module Scheduleservice
    module User
      module V1
        UserGroup = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bannote.scheduleservice.user.v1.UserGroup").msgclass
        UserGroupListResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bannote.scheduleservice.user.v1.UserGroupListResponse").msgclass
      end
    end
  end
end
