# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/enums.proto

require 'google/protobuf'


descriptor_data = "\n\x12\x63ommon/enums.proto\x12\x1d\x62\x61nnote.userservice.common.v1*\x80\x01\n\x08UserType\x12\x19\n\x15USER_TYPE_UNSPECIFIED\x10\x00\x12\x15\n\x11USER_TYPE_STUDENT\x10\x01\x12\x16\n\x12USER_TYPE_EMPLOYEE\x10\x02\x12\x15\n\x11USER_TYPE_SERVICE\x10\x03\x12\x13\n\x0fUSER_TYPE_OTHER\x10\x04*\xdc\x01\n\nUserStatus\x12\x1b\n\x17USER_STATUS_UNSPECIFIED\x10\x00\x12\x17\n\x13USER_STATUS_PENDING\x10\x01\x12\x16\n\x12USER_STATUS_ACTIVE\x10\x02\x12\x19\n\x15USER_STATUS_GRADUATED\x10\x03\x12\x15\n\x11USER_STATUS_LEAVE\x10\x04\x12\x19\n\x15USER_STATUS_SUSPENDED\x10\x05\x12\x19\n\x15USER_STATUS_WITHDRAWN\x10\x06\x12\x18\n\x14USER_STATUS_EXPELLED\x10\x07*\x7f\n\x12StudentClassStatus\x12$\n STUDENT_CLASS_STATUS_UNSPECIFIED\x10\x00\x12\x1f\n\x1bSTUDENT_CLASS_STATUS_ACTIVE\x10\x01\x12\"\n\x1eSTUDENT_CLASS_STATUS_GRADUATED\x10\x02*\xaf\x01\n\x08UserRole\x12\x19\n\x15USER_ROLE_UNSPECIFIED\x10\x00\x12\x15\n\x11USER_ROLE_STUDENT\x10\x01\x12\x18\n\x14USER_ROLE_DOORKEEPER\x10\x02\x12\x17\n\x13USER_ROLE_CLASS_REP\x10\x03\x12\x10\n\x0cUSER_ROLE_TA\x10\x04\x12\x17\n\x13USER_ROLE_PROFESSOR\x10\x05\x12\x13\n\x0fUSER_ROLE_ADMIN\x10\x06\x42\x89\x02\n!com.bannote.userservice.common.v1B\nEnumsProtoP\x01ZAgithub.com/kyumin1227/bannote-proto/gen/go/user-service/common/v1\xa2\x02\x03\x42UC\xaa\x02\x1d\x42\x61nnote.Userservice.Common.V1\xca\x02\x1d\x42\x61nnote\\Userservice\\Common\\V1\xe2\x02)Bannote\\Userservice\\Common\\V1\\GPBMetadata\xea\x02 Bannote::Userservice::Common::V1b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Bannote
  module Userservice
    module Common
      module V1
        UserType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bannote.userservice.common.v1.UserType").enummodule
        UserStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bannote.userservice.common.v1.UserStatus").enummodule
        StudentClassStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bannote.userservice.common.v1.StudentClassStatus").enummodule
        UserRole = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bannote.userservice.common.v1.UserRole").enummodule
      end
    end
  end
end
