# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/messages.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'


descriptor_data = "\n\x15\x63ommon/messages.proto\x12\x1d\x62\x61nnote.userservice.common.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfb\x01\n\tAuditInfo\x12\x39\n\ncreated_at\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\tcreatedAt\x12>\n\ndeleted_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x00R\tdeletedAt\x88\x01\x01\x12\"\n\ncreated_by\x18\x03 \x01(\tH\x01R\tcreatedBy\x88\x01\x01\x12\"\n\ndeleted_by\x18\x04 \x01(\tH\x02R\tdeletedBy\x88\x01\x01\x42\r\n\x0b_deleted_atB\r\n\x0b_created_byB\r\n\x0b_deleted_byB\x8c\x02\n!com.bannote.userservice.common.v1B\rMessagesProtoP\x01ZAgithub.com/kyumin1227/bannote-proto/gen/go/user-service/common/v1\xa2\x02\x03\x42UC\xaa\x02\x1d\x42\x61nnote.Userservice.Common.V1\xca\x02\x1d\x42\x61nnote\\Userservice\\Common\\V1\xe2\x02)Bannote\\Userservice\\Common\\V1\\GPBMetadata\xea\x02 Bannote::Userservice::Common::V1b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Bannote
  module Userservice
    module Common
      module V1
        AuditInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bannote.userservice.common.v1.AuditInfo").msgclass
      end
    end
  end
end
