# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schedule_file/schedule_file_service.proto

require 'google/protobuf'

require 'schedule_file/schedule_file_pb'


descriptor_data = "\n)schedule_file/schedule_file_service.proto\x12(bannote.scheduleservice.schedule_file.v1\x1a!schedule_file/schedule_file.proto\"1\n\x16GetScheduleFileRequest\x12\x17\n\x07\x66ile_id\x18\x01 \x01(\x03R\x06\x66ileId\"4\n\x19\x44\x65leteScheduleFileRequest\x12\x17\n\x07\x66ile_id\x18\x01 \x01(\x03R\x06\x66ileId\"6\n\x1a\x44\x65leteScheduleFileResponse\x12\x18\n\x07success\x18\x01 \x01(\x08R\x07success\"v\n\x17GetScheduleFileResponse\x12[\n\rschedule_file\x18\x01 \x01(\x0b\x32\x36.bannote.scheduleservice.schedule_file.v1.ScheduleFileR\x0cscheduleFile2\xd0\x02\n\x13ScheduleFileService\x12\x96\x01\n\x0fGetScheduleFile\x12@.bannote.scheduleservice.schedule_file.v1.GetScheduleFileRequest\x1a\x41.bannote.scheduleservice.schedule_file.v1.GetScheduleFileResponse\x12\x9f\x01\n\x12\x44\x65leteScheduleFile\x12\x43.bannote.scheduleservice.schedule_file.v1.DeleteScheduleFileRequest\x1a\x44.bannote.scheduleservice.schedule_file.v1.DeleteScheduleFileResponseB\x87\x02\n,com.bannote.scheduleservice.schedule_file.v1B\x18ScheduleFileServiceProtoP\x01\xa2\x02\x03\x42SS\xaa\x02\'Bannote.Scheduleservice.ScheduleFile.V1\xca\x02\'Bannote\\Scheduleservice\\ScheduleFile\\V1\xe2\x02\x33\x42\x61nnote\\Scheduleservice\\ScheduleFile\\V1\\GPBMetadata\xea\x02*Bannote::Scheduleservice::ScheduleFile::V1b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Bannote
  module Scheduleservice
    module ScheduleFile
      module V1
        GetScheduleFileRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bannote.scheduleservice.schedule_file.v1.GetScheduleFileRequest").msgclass
        DeleteScheduleFileRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bannote.scheduleservice.schedule_file.v1.DeleteScheduleFileRequest").msgclass
        DeleteScheduleFileResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bannote.scheduleservice.schedule_file.v1.DeleteScheduleFileResponse").msgclass
        GetScheduleFileResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bannote.scheduleservice.schedule_file.v1.GetScheduleFileResponse").msgclass
      end
    end
  end
end
