# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: schedule_file/schedule_file_service.proto for package 'Bannote.Scheduleservice.ScheduleFile.V1'

require 'grpc'
require 'schedule_file/schedule_file_service_pb'

module Bannote
  module Scheduleservice
    module ScheduleFile
      module V1
        module ScheduleFileService
          class Service

            include ::GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = 'bannote.scheduleservice.schedule_file.v1.ScheduleFileService'

            rpc :GetScheduleFile, ::Bannote::Scheduleservice::ScheduleFile::V1::GetScheduleFileRequest, ::Bannote::Scheduleservice::ScheduleFile::V1::GetScheduleFileResponse
            rpc :DeleteScheduleFile, ::Bannote::Scheduleservice::ScheduleFile::V1::DeleteScheduleFileRequest, ::Bannote::Scheduleservice::ScheduleFile::V1::DeleteScheduleFileResponse
          end

          Stub = Service.rpc_stub_class
        end
      end
    end
  end
end
