# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schedule_file/schedule_file.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'


descriptor_data = "\n!schedule_file/schedule_file.proto\x12(bannote.scheduleservice.schedule_file.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc8\x01\n\x0cScheduleFile\x12\x17\n\x07\x66ile_id\x18\x01 \x01(\x03R\x06\x66ileId\x12(\n\x10schedule_link_id\x18\x02 \x01(\x03R\x0escheduleLinkId\x12\x1b\n\tfile_path\x18\x03 \x01(\tR\x08\x66ilePath\x12\x1d\n\ncreated_by\x18\x04 \x01(\x03R\tcreatedBy\x12\x39\n\ncreated_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\tcreatedAtB\x80\x02\n,com.bannote.scheduleservice.schedule_file.v1B\x11ScheduleFileProtoP\x01\xa2\x02\x03\x42SS\xaa\x02\'Bannote.Scheduleservice.ScheduleFile.V1\xca\x02\'Bannote\\Scheduleservice\\ScheduleFile\\V1\xe2\x02\x33\x42\x61nnote\\Scheduleservice\\ScheduleFile\\V1\\GPBMetadata\xea\x02*Bannote::Scheduleservice::ScheduleFile::V1b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Bannote
  module Scheduleservice
    module ScheduleFile
      module V1
        ScheduleFile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bannote.scheduleservice.schedule_file.v1.ScheduleFile").msgclass
      end
    end
  end
end
