# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: room_operating_hour/service.proto for package 'Bannote.Studyroomservice.Roomoperatinghour.V1'

require 'grpc'
require 'room_operating_hour/service_pb'

module Bannote
  module Studyroomservice
    module Roomoperatinghour
      module V1
        module RoomOperatingHourService
          # ================================
          # RoomOperatingHour Service
          # - 스터디룸의 요일별 운영 시간을 관리하는 서비스
          # ================================
          class Service

            include ::GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = 'bannote.studyroomservice.roomoperatinghour.v1.RoomOperatingHourService'

            # 스터디룸 운영 시간 생성
            rpc :CreateRoomOperatingHour, ::Bannote::Studyroomservice::Roomoperatinghour::V1::CreateRoomOperatingHourRequest, ::Bannote::Studyroomservice::Roomoperatinghour::V1::CreateRoomOperatingHourResponse
            # 특정 스터디룸 운영 시간 조회
            rpc :GetRoomOperatingHour, ::Bannote::Studyroomservice::Roomoperatinghour::V1::GetRoomOperatingHourRequest, ::Bannote::Studyroomservice::Roomoperatinghour::V1::GetRoomOperatingHourResponse
            # 스터디룸 운영 시간 목록 조회
            rpc :ListRoomOperatingHours, ::Bannote::Studyroomservice::Roomoperatinghour::V1::ListRoomOperatingHoursRequest, ::Bannote::Studyroomservice::Roomoperatinghour::V1::ListRoomOperatingHoursResponse
            # 스터디룸 운영 시간 정보 업데이트
            rpc :UpdateRoomOperatingHour, ::Bannote::Studyroomservice::Roomoperatinghour::V1::UpdateRoomOperatingHourRequest, ::Bannote::Studyroomservice::Roomoperatinghour::V1::UpdateRoomOperatingHourResponse
            # 스터디룸 운영 시간 삭제 (소프트 삭제)
            rpc :DeleteRoomOperatingHour, ::Bannote::Studyroomservice::Roomoperatinghour::V1::DeleteRoomOperatingHourRequest, ::Bannote::Studyroomservice::Roomoperatinghour::V1::DeleteRoomOperatingHourResponse
          end

          Stub = Service.rpc_stub_class
        end
      end
    end
  end
end
