# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: room_operating_hour/service.proto

require 'google/protobuf'

require 'room_operating_hour/room_operating_hour_pb'


descriptor_data = "\n!room_operating_hour/service.proto\x12 studyroom.room_operating_hour.v1\x1a-room_operating_hour/room_operating_hour.proto2\xb3\x06\n\x18RoomOperatingHourService\x12\x9e\x01\n\x17\x43reateRoomOperatingHour\x12@.studyroom.room_operating_hour.v1.CreateRoomOperatingHourRequest\x1a\x41.studyroom.room_operating_hour.v1.CreateRoomOperatingHourResponse\x12\x95\x01\n\x14GetRoomOperatingHour\x12=.studyroom.room_operating_hour.v1.GetRoomOperatingHourRequest\x1a>.studyroom.room_operating_hour.v1.GetRoomOperatingHourResponse\x12\x9b\x01\n\x16ListRoomOperatingHours\x12?.studyroom.room_operating_hour.v1.ListRoomOperatingHoursRequest\x1a@.studyroom.room_operating_hour.v1.ListRoomOperatingHoursResponse\x12\x9e\x01\n\x17UpdateRoomOperatingHour\x12@.studyroom.room_operating_hour.v1.UpdateRoomOperatingHourRequest\x1a\x41.studyroom.room_operating_hour.v1.UpdateRoomOperatingHourResponse\x12\x9e\x01\n\x17\x44\x65leteRoomOperatingHour\x12@.studyroom.room_operating_hour.v1.DeleteRoomOperatingHourRequest\x1a\x41.studyroom.room_operating_hour.v1.DeleteRoomOperatingHourResponseb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Studyroom
  module RoomOperatingHour
    module V1
    end
  end
end
