# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: room_operating_hour/service.proto

require 'google/protobuf'

require 'room_operating_hour/room_operating_hour_pb'


descriptor_data = "\n!room_operating_hour/service.proto\x12-bannote.studyroomservice.roomoperatinghour.v1\x1a-room_operating_hour/room_operating_hour.proto2\xb5\x07\n\x18RoomOperatingHourService\x12\xb8\x01\n\x17\x43reateRoomOperatingHour\x12M.bannote.studyroomservice.roomoperatinghour.v1.CreateRoomOperatingHourRequest\x1aN.bannote.studyroomservice.roomoperatinghour.v1.CreateRoomOperatingHourResponse\x12\xaf\x01\n\x14GetRoomOperatingHour\x12J.bannote.studyroomservice.roomoperatinghour.v1.GetRoomOperatingHourRequest\x1aK.bannote.studyroomservice.roomoperatinghour.v1.GetRoomOperatingHourResponse\x12\xb5\x01\n\x16ListRoomOperatingHours\x12L.bannote.studyroomservice.roomoperatinghour.v1.ListRoomOperatingHoursRequest\x1aM.bannote.studyroomservice.roomoperatinghour.v1.ListRoomOperatingHoursResponse\x12\xb8\x01\n\x17UpdateRoomOperatingHour\x12M.bannote.studyroomservice.roomoperatinghour.v1.UpdateRoomOperatingHourRequest\x1aN.bannote.studyroomservice.roomoperatinghour.v1.UpdateRoomOperatingHourResponse\x12\xb8\x01\n\x17\x44\x65leteRoomOperatingHour\x12M.bannote.studyroomservice.roomoperatinghour.v1.DeleteRoomOperatingHourRequest\x1aN.bannote.studyroomservice.roomoperatinghour.v1.DeleteRoomOperatingHourResponseB\x98\x02\n1com.bannote.studyroomservice.roomoperatinghour.v1B\x0cServiceProtoP\x01\xa2\x02\x03\x42SR\xaa\x02-Bannote.Studyroomservice.Roomoperatinghour.V1\xca\x02-Bannote\\Studyroomservice\\Roomoperatinghour\\V1\xe2\x02\x39\x42\x61nnote\\Studyroomservice\\Roomoperatinghour\\V1\\GPBMetadata\xea\x02\x30\x42\x61nnote::Studyroomservice::Roomoperatinghour::V1b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Bannote
  module Studyroomservice
    module Roomoperatinghour
      module V1
      end
    end
  end
end
