# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: room_operating_hour/service.proto for package 'studyroom.room_operating_hour.v1'

require 'grpc'
require 'room_operating_hour/service_pb'

module Studyroom
  module RoomOperatingHour
    module V1
      module RoomOperatingHourService
        # RoomOperatingHour 서비스 정의
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'studyroom.room_operating_hour.v1.RoomOperatingHourService'

          # 스터디룸 운영 시간 생성
          rpc :CreateRoomOperatingHour, ::Studyroom::RoomOperatingHour::V1::CreateRoomOperatingHourRequest, ::Studyroom::RoomOperatingHour::V1::CreateRoomOperatingHourResponse
          # 특정 스터디룸 운영 시간 조회
          rpc :GetRoomOperatingHour, ::Studyroom::RoomOperatingHour::V1::GetRoomOperatingHourRequest, ::Studyroom::RoomOperatingHour::V1::GetRoomOperatingHourResponse
          # 스터디룸 운영 시간 목록 조회
          rpc :ListRoomOperatingHours, ::Studyroom::RoomOperatingHour::V1::ListRoomOperatingHoursRequest, ::Studyroom::RoomOperatingHour::V1::ListRoomOperatingHoursResponse
          # 스터디룸 운영 시간 정보 업데이트
          rpc :UpdateRoomOperatingHour, ::Studyroom::RoomOperatingHour::V1::UpdateRoomOperatingHourRequest, ::Studyroom::RoomOperatingHour::V1::UpdateRoomOperatingHourResponse
          # 스터디룸 운영 시간 삭제 (소프트 삭제)
          rpc :DeleteRoomOperatingHour, ::Studyroom::RoomOperatingHour::V1::DeleteRoomOperatingHourRequest, ::Studyroom::RoomOperatingHour::V1::DeleteRoomOperatingHourResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
