# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: placeholder.proto

require 'google/protobuf'

require 'reservation/service_pb'


descriptor_data = "\n\x11placeholder.proto\x12\x17reservation.consumer.v1\x1a\x19reservation/service.protob\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Reservation
  module Consumer
    module V1
    end
  end
end
