# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: group/group_service.proto for package 'Bannote.Scheduleservice.Group.V1'

require 'grpc'
require 'group/group_service_pb'

module Bannote
  module Scheduleservice
    module Group
      module V1
        module GroupService
          # ================================
          # Group Service 정의
          # ================================
          class Service

            include ::GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = 'bannote.scheduleservice.group.v1.GroupService'

            rpc :CreateGroup, ::Bannote::Scheduleservice::Group::V1::CreateGroupRequest, ::Bannote::Scheduleservice::Group::V1::CreateGroupResponse
            rpc :GetGroupList, ::Bannote::Scheduleservice::Group::V1::GetGroupListRequest, ::Bannote::Scheduleservice::Group::V1::GetGroupListResponse
            rpc :GetGroup, ::Bannote::Scheduleservice::Group::V1::GetGroupRequest, ::Bannote::Scheduleservice::Group::V1::GetGroupResponse
            rpc :UpdateGroup, ::Bannote::Scheduleservice::Group::V1::UpdateGroupRequest, ::Bannote::Scheduleservice::Group::V1::UpdateGroupResponse
            rpc :DeleteGroup, ::Bannote::Scheduleservice::Group::V1::DeleteGroupRequest, ::Bannote::Scheduleservice::Group::V1::DeleteGroupResponse
          end

          Stub = Service.rpc_stub_class
        end
      end
    end
  end
end
