# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: group/group.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
require 'tag/tag_pb'


descriptor_data = "\n\x11group/group.proto\x12 bannote.scheduleservice.group.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\rtag/tag.proto\"\x86\x05\n\x05Group\x12\x19\n\x08group_id\x18\x01 \x01(\x03R\x07groupId\x12\x1d\n\ngroup_code\x18\x02 \x01(\tR\tgroupCode\x12\"\n\rgroup_type_id\x18\x03 \x01(\x03R\x0bgroupTypeId\x12\x1d\n\ngroup_name\x18\x04 \x01(\tR\tgroupName\x12+\n\x11group_description\x18\x05 \x01(\tR\x10groupDescription\x12\x1b\n\tis_public\x18\x06 \x01(\x08R\x08isPublic\x12!\n\x0cis_published\x18\x07 \x01(\x08R\x0bisPublished\x12#\n\rcolor_default\x18\x08 \x01(\tR\x0c\x63olorDefault\x12\'\n\x0f\x63olor_highlight\x18\t \x01(\tR\x0e\x63olorHighlight\x12\x39\n\ncreated_at\x18\n \x01(\x0b\x32\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x39\n\nupdated_at\x18\x0b \x01(\x0b\x32\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x39\n\ndeleted_at\x18\x0c \x01(\x0b\x32\x1a.google.protobuf.TimestampR\tdeletedAt\x12\x1d\n\ncreated_by\x18\r \x01(\x03R\tcreatedBy\x12\x1d\n\nupdated_by\x18\x0e \x01(\x03R\tupdatedBy\x12\x1d\n\ndeleted_by\x18\x0f \x01(\x03R\tdeletedBy\x12\x37\n\x04tags\x18\x10 \x03(\x0b\x32#.bannote.scheduleservice.tag.v1.TagR\x04tags\"T\n\x11GroupListResponse\x12?\n\x06groups\x18\x01 \x03(\x0b\x32\'.bannote.scheduleservice.group.v1.GroupR\x06groupsB\xd5\x01\n$com.bannote.scheduleservice.group.v1B\nGroupProtoP\x01\xa2\x02\x03\x42SG\xaa\x02 Bannote.Scheduleservice.Group.V1\xca\x02 Bannote\\Scheduleservice\\Group\\V1\xe2\x02,Bannote\\Scheduleservice\\Group\\V1\\GPBMetadata\xea\x02#Bannote::Scheduleservice::Group::V1b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Bannote
  module Scheduleservice
    module Group
      module V1
        Group = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bannote.scheduleservice.group.v1.Group").msgclass
        GroupListResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bannote.scheduleservice.group.v1.GroupListResponse").msgclass
      end
    end
  end
end
