# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: studentclass/service.proto for package 'Bannote.Userservice.Studentclass.V1'

require 'grpc'
require 'studentclass/service_pb'

module Bannote
  module Userservice
    module Studentclass
      module V1
        module StudentClassService
          # Gateway에서 gRPC metadata로 전달되는 정보:
          # - user-id: 요청하는 유저의 ID
          # - user-role: 요청하는 유저의 역할 (ADMIN, STUDENT, EMPLOYEE 등)
          #
          # The student class service definition.
          class Service

            include ::GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = 'bannote.userservice.studentclass.v1.StudentClassService'

            #  학반 ID로 학반 조회 API
            rpc :GetStudentClass, ::Bannote::Userservice::Studentclass::V1::GetStudentClassRequest, ::Bannote::Userservice::Studentclass::V1::GetStudentClassResponse
            #  학반 생성 API
            rpc :CreateStudentClass, ::Bannote::Userservice::Studentclass::V1::CreateStudentClassRequest, ::Bannote::Userservice::Studentclass::V1::CreateStudentClassResponse
            #  학반 수정 API
            rpc :UpdateStudentClass, ::Bannote::Userservice::Studentclass::V1::UpdateStudentClassRequest, ::Bannote::Userservice::Studentclass::V1::UpdateStudentClassResponse
            #  학반 삭제 API
            rpc :DeleteStudentClass, ::Bannote::Userservice::Studentclass::V1::DeleteStudentClassRequest, ::Bannote::Userservice::Studentclass::V1::DeleteStudentClassResponse
            #  학반 목록 조회 API
            rpc :ListStudentClasses, ::Bannote::Userservice::Studentclass::V1::ListStudentClassesRequest, ::Bannote::Userservice::Studentclass::V1::ListStudentClassesResponse
          end

          Stub = Service.rpc_stub_class
        end
      end
    end
  end
end
