# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: studentclass/studentclass.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
require 'common/enums_pb'
require 'common/messages_pb'


descriptor_data = "\n\x1fstudentclass/studentclass.proto\x12#bannote.userservice.studentclass.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x12\x63ommon/enums.proto\x1a\x15\x63ommon/messages.proto\"\xa9\x03\n\x0cStudentClass\x12,\n\x12student_class_code\x18\x01 \x01(\tR\x10studentClassCode\x12\'\n\x0f\x64\x65partment_code\x18\x02 \x01(\tR\x0e\x64\x65partmentCode\x12\x12\n\x04name\x18\x03 \x01(\tR\x04name\x12%\n\x0e\x61\x64mission_year\x18\x04 \x01(\x05R\radmissionYear\x12\'\n\x0fgraduation_year\x18\x05 \x01(\x05R\x0egraduationYear\x12I\n\x06status\x18\x06 \x01(\x0e\x32\x31.bannote.userservice.common.v1.StudentClassStatusR\x06status\x12\x39\n\ncreated_at\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x39\n\ndeleted_at\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\tdeletedAt\x12\x1d\n\ncreated_by\x18\t \x01(\tR\tcreatedBy\"\xb8\x01\n\x15StudentClassWithAudit\x12V\n\rstudent_class\x18\x01 \x01(\x0b\x32\x31.bannote.userservice.studentclass.v1.StudentClassR\x0cstudentClass\x12G\n\naudit_info\x18\x02 \x01(\x0b\x32(.bannote.userservice.common.v1.AuditInfoR\tauditInfoB\xb5\x02\n\'com.bannote.userservice.studentclass.v1B\x11StudentclassProtoP\x01ZHgithub.com/kyumin1227/bannote-proto/gen/go/user-service/student_class/v1\xa2\x02\x03\x42US\xaa\x02#Bannote.Userservice.Studentclass.V1\xca\x02#Bannote\\Userservice\\Studentclass\\V1\xe2\x02/Bannote\\Userservice\\Studentclass\\V1\\GPBMetadata\xea\x02&Bannote::Userservice::Studentclass::V1b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Bannote
  module Userservice
    module Studentclass
      module V1
        StudentClass = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bannote.userservice.studentclass.v1.StudentClass").msgclass
        StudentClassWithAudit = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bannote.userservice.studentclass.v1.StudentClassWithAudit").msgclass
      end
    end
  end
end
