# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: group_tag/group_tag_service.proto

require 'google/protobuf'

require 'tag/tag_pb'
require 'group_tag/group_tag_pb'


descriptor_data = "\n!group_tag/group_tag_service.proto\x12$bannote.scheduleservice.group_tag.v1\x1a\rtag/tag.proto\x1a\x19group_tag/group_tag.proto\"H\n\x14\x41\x64\x64TagToGroupRequest\x12\x19\n\x08group_id\x18\x01 \x01(\x03R\x07groupId\x12\x15\n\x06tag_id\x18\x02 \x01(\x03R\x05tagId\"2\n\x15GetTagsOfGroupRequest\x12\x19\n\x08group_id\x18\x01 \x01(\x03R\x07groupId\"M\n\x19RemoveTagFromGroupRequest\x12\x19\n\x08group_id\x18\x01 \x01(\x03R\x07groupId\x12\x15\n\x06tag_id\x18\x02 \x01(\x03R\x05tagId\"6\n\x1aRemoveTagFromGroupResponse\x12\x18\n\x07success\x18\x01 \x01(\x08R\x07success\"d\n\x15\x41\x64\x64TagToGroupResponse\x12K\n\tgroup_tag\x18\x01 \x01(\x0b\x32..bannote.scheduleservice.group_tag.v1.GroupTagR\x08groupTag\"Q\n\x16GetTagsOfGroupResponse\x12\x37\n\x04tags\x18\x01 \x03(\x0b\x32#.bannote.scheduleservice.tag.v1.TagR\x04tags2\xc4\x03\n\x0fGroupTagService\x12\x88\x01\n\rAddTagToGroup\x12:.bannote.scheduleservice.group_tag.v1.AddTagToGroupRequest\x1a;.bannote.scheduleservice.group_tag.v1.AddTagToGroupResponse\x12\x8b\x01\n\x0eGetTagsOfGroup\x12;.bannote.scheduleservice.group_tag.v1.GetTagsOfGroupRequest\x1a<.bannote.scheduleservice.group_tag.v1.GetTagsOfGroupResponse\x12\x97\x01\n\x12RemoveTagFromGroup\x12?.bannote.scheduleservice.group_tag.v1.RemoveTagFromGroupRequest\x1a@.bannote.scheduleservice.group_tag.v1.RemoveTagFromGroupResponseB\xef\x01\n(com.bannote.scheduleservice.group_tag.v1B\x14GroupTagServiceProtoP\x01\xa2\x02\x03\x42SG\xaa\x02#Bannote.Scheduleservice.GroupTag.V1\xca\x02#Bannote\\Scheduleservice\\GroupTag\\V1\xe2\x02/Bannote\\Scheduleservice\\GroupTag\\V1\\GPBMetadata\xea\x02&Bannote::Scheduleservice::GroupTag::V1b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Bannote
  module Scheduleservice
    module GroupTag
      module V1
        AddTagToGroupRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bannote.scheduleservice.group_tag.v1.AddTagToGroupRequest").msgclass
        GetTagsOfGroupRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bannote.scheduleservice.group_tag.v1.GetTagsOfGroupRequest").msgclass
        RemoveTagFromGroupRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bannote.scheduleservice.group_tag.v1.RemoveTagFromGroupRequest").msgclass
        RemoveTagFromGroupResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bannote.scheduleservice.group_tag.v1.RemoveTagFromGroupResponse").msgclass
        AddTagToGroupResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bannote.scheduleservice.group_tag.v1.AddTagToGroupResponse").msgclass
        GetTagsOfGroupResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bannote.scheduleservice.group_tag.v1.GetTagsOfGroupResponse").msgclass
      end
    end
  end
end
