# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: group_tag/group_tag_service.proto for package 'Bannote.Scheduleservice.GroupTag.V1'

require 'grpc'
require 'group_tag/group_tag_service_pb'

module Bannote
  module Scheduleservice
    module GroupTag
      module V1
        module GroupTagService
          class Service

            include ::GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = 'bannote.scheduleservice.group_tag.v1.GroupTagService'

            rpc :AddTagToGroup, ::Bannote::Scheduleservice::GroupTag::V1::AddTagToGroupRequest, ::Bannote::Scheduleservice::GroupTag::V1::AddTagToGroupResponse
            rpc :GetTagsOfGroup, ::Bannote::Scheduleservice::GroupTag::V1::GetTagsOfGroupRequest, ::Bannote::Scheduleservice::GroupTag::V1::GetTagsOfGroupResponse
            rpc :RemoveTagFromGroup, ::Bannote::Scheduleservice::GroupTag::V1::RemoveTagFromGroupRequest, ::Bannote::Scheduleservice::GroupTag::V1::RemoveTagFromGroupResponse
          end

          Stub = Service.rpc_stub_class
        end
      end
    end
  end
end
