# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: schedule/schedule_service.proto for package 'Bannote.Scheduleservice.Schedule.V1'

require 'grpc'
require 'schedule/schedule_service_pb'

module Bannote
  module Scheduleservice
    module Schedule
      module V1
        module ScheduleService
          class Service

            include ::GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = 'bannote.scheduleservice.schedule.v1.ScheduleService'

            rpc :CreateSchedule, ::Bannote::Scheduleservice::Schedule::V1::CreateScheduleRequest, ::Bannote::Scheduleservice::Schedule::V1::CreateScheduleResponse
            rpc :GetScheduleList, ::Bannote::Scheduleservice::Schedule::V1::GetScheduleListRequest, ::Bannote::Scheduleservice::Schedule::V1::GetScheduleListResponse
            rpc :GetSchedule, ::Bannote::Scheduleservice::Schedule::V1::GetScheduleRequest, ::Bannote::Scheduleservice::Schedule::V1::GetScheduleResponse
            rpc :UpdateSchedule, ::Bannote::Scheduleservice::Schedule::V1::UpdateScheduleRequest, ::Bannote::Scheduleservice::Schedule::V1::UpdateScheduleResponse
            rpc :DeleteSchedule, ::Bannote::Scheduleservice::Schedule::V1::DeleteScheduleRequest, ::Bannote::Scheduleservice::Schedule::V1::DeleteScheduleResponse
          end

          Stub = Service.rpc_stub_class
        end
      end
    end
  end
end
