# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schedule/schedule.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'


descriptor_data = "\n\x17schedule/schedule.proto\x12#bannote.scheduleservice.schedule.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbd\x04\n\x08Schedule\x12\x1f\n\x0bschedule_id\x18\x01 \x01(\x03R\nscheduleId\x12\x12\n\x04\x63ode\x18\x02 \x01(\tR\x04\x63ode\x12\x19\n\x08group_id\x18\x03 \x01(\x03R\x07groupId\x12-\n\x10schedule_link_id\x18\x04 \x01(\x03H\x00R\x0escheduleLinkId\x88\x01\x01\x12\x1d\n\x07\x63omment\x18\x05 \x01(\tH\x01R\x07\x63omment\x88\x01\x01\x12\x14\n\x05\x63olor\x18\x06 \x01(\tR\x05\x63olor\x12\x39\n\ncreated_at\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\tcreatedAt\x12>\n\nupdated_at\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x02R\tupdatedAt\x88\x01\x01\x12>\n\ndeleted_at\x18\t \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x03R\tdeletedAt\x88\x01\x01\x12\x1d\n\ncreated_by\x18\n \x01(\x03R\tcreatedBy\x12\"\n\nupdated_by\x18\x0b \x01(\x03H\x04R\tupdatedBy\x88\x01\x01\x12\"\n\ndeleted_by\x18\x0c \x01(\x03H\x05R\tdeletedBy\x88\x01\x01\x42\x13\n\x11_schedule_link_idB\n\n\x08_commentB\r\n\x0b_updated_atB\r\n\x0b_deleted_atB\r\n\x0b_updated_byB\r\n\x0b_deleted_by\"c\n\x14ScheduleListResponse\x12K\n\tschedules\x18\x01 \x03(\x0b\x32-.bannote.scheduleservice.schedule.v1.ScheduleR\tschedulesB\xe7\x01\n\'com.bannote.scheduleservice.schedule.v1B\rScheduleProtoP\x01\xa2\x02\x03\x42SS\xaa\x02#Bannote.Scheduleservice.Schedule.V1\xca\x02#Bannote\\Scheduleservice\\Schedule\\V1\xe2\x02/Bannote\\Scheduleservice\\Schedule\\V1\\GPBMetadata\xea\x02&Bannote::Scheduleservice::Schedule::V1b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Bannote
  module Scheduleservice
    module Schedule
      module V1
        Schedule = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bannote.scheduleservice.schedule.v1.Schedule").msgclass
        ScheduleListResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bannote.scheduleservice.schedule.v1.ScheduleListResponse").msgclass
      end
    end
  end
end
