# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: room/room.proto

require 'google/protobuf'


descriptor_data = "\n\x0froom/room.proto\x12\x11studyroom.room.v1\"\xeb\x01\n\x04Room\x12\x0e\n\x02id\x18\x01 \x01(\x03R\x02id\x12#\n\rdepartment_id\x18\x02 \x01(\x03R\x0c\x64\x65partmentId\x12\x12\n\x04name\x18\x03 \x01(\tR\x04name\x12%\n\x0eminimum_member\x18\x04 \x01(\x05R\rminimumMember\x12\x35\n\x06status\x18\x05 \x01(\x0e\x32\x1d.studyroom.room.v1.RoomStatusR\x06status\x12\x1d\n\ncreated_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n\nupdated_at\x18\x07 \x01(\tR\tupdatedAt\"\xaa\x01\n\x11\x43reateRoomRequest\x12#\n\rdepartment_id\x18\x01 \x01(\x03R\x0c\x64\x65partmentId\x12\x12\n\x04name\x18\x02 \x01(\tR\x04name\x12%\n\x0eminimum_member\x18\x03 \x01(\x05R\rminimumMember\x12\x35\n\x06status\x18\x04 \x01(\x0e\x32\x1d.studyroom.room.v1.RoomStatusR\x06status\" \n\x0eGetRoomRequest\x12\x0e\n\x02id\x18\x01 \x01(\x03R\x02id\"\x12\n\x10ListRoomsRequest\"A\n\x12\x43reateRoomResponse\x12+\n\x04room\x18\x01 \x01(\x0b\x32\x17.studyroom.room.v1.RoomR\x04room\">\n\x0fGetRoomResponse\x12+\n\x04room\x18\x01 \x01(\x0b\x32\x17.studyroom.room.v1.RoomR\x04room\"B\n\x11ListRoomsResponse\x12-\n\x05rooms\x18\x01 \x03(\x0b\x32\x17.studyroom.room.v1.RoomR\x05rooms\"A\n\x12UpdateRoomResponse\x12+\n\x04room\x18\x01 \x01(\x0b\x32\x17.studyroom.room.v1.RoomR\x04room\"\x14\n\x12\x44\x65leteRoomResponse\"\xba\x01\n\x11UpdateRoomRequest\x12\x0e\n\x02id\x18\x01 \x01(\x03R\x02id\x12#\n\rdepartment_id\x18\x02 \x01(\x03R\x0c\x64\x65partmentId\x12\x12\n\x04name\x18\x03 \x01(\tR\x04name\x12%\n\x0eminimum_member\x18\x04 \x01(\x05R\rminimumMember\x12\x35\n\x06status\x18\x05 \x01(\x0e\x32\x1d.studyroom.room.v1.RoomStatusR\x06status\"#\n\x11\x44\x65leteRoomRequest\x12\x0e\n\x02id\x18\x01 \x01(\x03R\x02id*[\n\nRoomStatus\x12\x1b\n\x17ROOM_STATUS_UNSPECIFIED\x10\x00\x12\x16\n\x12ROOM_STATUS_VACANT\x10\x01\x12\x18\n\x14ROOM_STATUS_OCCUPIED\x10\x02\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Studyroom
  module Room
    module V1
      Room = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("studyroom.room.v1.Room").msgclass
      CreateRoomRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("studyroom.room.v1.CreateRoomRequest").msgclass
      GetRoomRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("studyroom.room.v1.GetRoomRequest").msgclass
      ListRoomsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("studyroom.room.v1.ListRoomsRequest").msgclass
      CreateRoomResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("studyroom.room.v1.CreateRoomResponse").msgclass
      GetRoomResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("studyroom.room.v1.GetRoomResponse").msgclass
      ListRoomsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("studyroom.room.v1.ListRoomsResponse").msgclass
      UpdateRoomResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("studyroom.room.v1.UpdateRoomResponse").msgclass
      DeleteRoomResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("studyroom.room.v1.DeleteRoomResponse").msgclass
      UpdateRoomRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("studyroom.room.v1.UpdateRoomRequest").msgclass
      DeleteRoomRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("studyroom.room.v1.DeleteRoomRequest").msgclass
      RoomStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("studyroom.room.v1.RoomStatus").enummodule
    end
  end
end
