# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: room/service.proto

require 'google/protobuf'

require 'room/room_pb'


descriptor_data = "\n\x12room/service.proto\x12\x11studyroom.room.v1\x1a\x0froom/room.proto2\xc8\x03\n\x0bRoomService\x12Y\n\nCreateRoom\x12$.studyroom.room.v1.CreateRoomRequest\x1a%.studyroom.room.v1.CreateRoomResponse\x12P\n\x07GetRoom\x12!.studyroom.room.v1.GetRoomRequest\x1a\".studyroom.room.v1.GetRoomResponse\x12V\n\tListRooms\x12#.studyroom.room.v1.ListRoomsRequest\x1a$.studyroom.room.v1.ListRoomsResponse\x12Y\n\nUpdateRoom\x12$.studyroom.room.v1.UpdateRoomRequest\x1a%.studyroom.room.v1.UpdateRoomResponse\x12Y\n\nDeleteRoom\x12$.studyroom.room.v1.DeleteRoomRequest\x1a%.studyroom.room.v1.DeleteRoomResponseb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Studyroom
  module Room
    module V1
    end
  end
end
