# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: room/service.proto for package 'studyroom.room.v1'

require 'grpc'
require 'room/service_pb'

module Studyroom
  module Room
    module V1
      module RoomService
        # Room 서비스 정의
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'studyroom.room.v1.RoomService'

          # 스터디룸 생성
          rpc :CreateRoom, ::Studyroom::Room::V1::CreateRoomRequest, ::Studyroom::Room::V1::CreateRoomResponse
          # 특정 스터디룸 조회
          rpc :GetRoom, ::Studyroom::Room::V1::GetRoomRequest, ::Studyroom::Room::V1::GetRoomResponse
          # 모든 스터디룸 목록 조회
          rpc :ListRooms, ::Studyroom::Room::V1::ListRoomsRequest, ::Studyroom::Room::V1::ListRoomsResponse
          # 스터디룸 정보 업데이트
          rpc :UpdateRoom, ::Studyroom::Room::V1::UpdateRoomRequest, ::Studyroom::Room::V1::UpdateRoomResponse
          # 스터디룸 삭제
          rpc :DeleteRoom, ::Studyroom::Room::V1::DeleteRoomRequest, ::Studyroom::Room::V1::DeleteRoomResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
