# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: room/service.proto for package 'Bannote.Studyroomservice.Room.V1'

require 'grpc'
require 'room/service_pb'

module Bannote
  module Studyroomservice
    module Room
      module V1
        module RoomService
          # ================================
          # Room Service
          # - 스터디룸 생성, 조회, 수정, 삭제를 담당하는 서비스
          # ================================
          class Service

            include ::GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = 'bannote.studyroomservice.room.v1.RoomService'

            # 스터디룸 생성
            rpc :CreateRoom, ::Bannote::Studyroomservice::Room::V1::CreateRoomRequest, ::Bannote::Studyroomservice::Room::V1::CreateRoomResponse
            # 특정 스터디룸 조회
            rpc :GetRoom, ::Bannote::Studyroomservice::Room::V1::GetRoomRequest, ::Bannote::Studyroomservice::Room::V1::GetRoomResponse
            # 스터디룸 목록 조회
            rpc :ListRooms, ::Bannote::Studyroomservice::Room::V1::ListRoomsRequest, ::Bannote::Studyroomservice::Room::V1::ListRoomsResponse
            # 스터디룸 정보 업데이트
            rpc :UpdateRoom, ::Bannote::Studyroomservice::Room::V1::UpdateRoomRequest, ::Bannote::Studyroomservice::Room::V1::UpdateRoomResponse
            # 스터디룸 삭제
            rpc :DeleteRoom, ::Bannote::Studyroomservice::Room::V1::DeleteRoomRequest, ::Bannote::Studyroomservice::Room::V1::DeleteRoomResponse
          end

          Stub = Service.rpc_stub_class
        end
      end
    end
  end
end
