# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tag/tag.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'


descriptor_data = "\n\rtag/tag.proto\x12\x1e\x62\x61nnote.scheduleservice.tag.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8a\x01\n\x03Tag\x12\x15\n\x06tag_id\x18\x01 \x01(\x03R\x05tagId\x12\x12\n\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n\ncreated_by\x18\x03 \x01(\x03R\tcreatedBy\x12\x39\n\ncreated_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\tcreatedAt\"J\n\x0fTagListResponse\x12\x37\n\x04tags\x18\x01 \x03(\x0b\x32#.bannote.scheduleservice.tag.v1.TagR\x04tagsB\xc9\x01\n\"com.bannote.scheduleservice.tag.v1B\x08TagProtoP\x01\xa2\x02\x03\x42ST\xaa\x02\x1e\x42\x61nnote.Scheduleservice.Tag.V1\xca\x02\x1e\x42\x61nnote\\Scheduleservice\\Tag\\V1\xe2\x02*Bannote\\Scheduleservice\\Tag\\V1\\GPBMetadata\xea\x02!Bannote::Scheduleservice::Tag::V1b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Bannote
  module Scheduleservice
    module Tag
      module V1
        Tag = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bannote.scheduleservice.tag.v1.Tag").msgclass
        TagListResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bannote.scheduleservice.tag.v1.TagListResponse").msgclass
      end
    end
  end
end
