# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tag/tag_service.proto

require 'google/protobuf'

require 'tag/tag_pb'


descriptor_data = "\n\x15tag/tag_service.proto\x12\x1e\x62\x61nnote.scheduleservice.tag.v1\x1a\rtag/tag.proto\"&\n\x10\x43reateTagRequest\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\"&\n\rGetTagRequest\x12\x15\n\x06tag_id\x18\x01 \x01(\x03R\x05tagId\")\n\x10\x44\x65leteTagRequest\x12\x15\n\x06tag_id\x18\x01 \x01(\x03R\x05tagId\"-\n\x11\x44\x65leteTagResponse\x12\x18\n\x07success\x18\x01 \x01(\x08R\x07success\"J\n\x11\x43reateTagResponse\x12\x35\n\x03tag\x18\x01 \x01(\x0b\x32#.bannote.scheduleservice.tag.v1.TagR\x03tag\"G\n\x0eGetTagResponse\x12\x35\n\x03tag\x18\x01 \x01(\x0b\x32#.bannote.scheduleservice.tag.v1.TagR\x03tag\"\x13\n\x11GetTagListRequest\"q\n\x12GetTagListResponse\x12[\n\x11tag_list_response\x18\x01 \x01(\x0b\x32/.bannote.scheduleservice.tag.v1.TagListResponseR\x0ftagListResponse2\xce\x03\n\nTagService\x12p\n\tCreateTag\x12\x30.bannote.scheduleservice.tag.v1.CreateTagRequest\x1a\x31.bannote.scheduleservice.tag.v1.CreateTagResponse\x12g\n\x06GetTag\x12-.bannote.scheduleservice.tag.v1.GetTagRequest\x1a..bannote.scheduleservice.tag.v1.GetTagResponse\x12s\n\nGetTagList\x12\x31.bannote.scheduleservice.tag.v1.GetTagListRequest\x1a\x32.bannote.scheduleservice.tag.v1.GetTagListResponse\x12p\n\tDeleteTag\x12\x30.bannote.scheduleservice.tag.v1.DeleteTagRequest\x1a\x31.bannote.scheduleservice.tag.v1.DeleteTagResponseB\xd0\x01\n\"com.bannote.scheduleservice.tag.v1B\x0fTagServiceProtoP\x01\xa2\x02\x03\x42ST\xaa\x02\x1e\x42\x61nnote.Scheduleservice.Tag.V1\xca\x02\x1e\x42\x61nnote\\Scheduleservice\\Tag\\V1\xe2\x02*Bannote\\Scheduleservice\\Tag\\V1\\GPBMetadata\xea\x02!Bannote::Scheduleservice::Tag::V1b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Bannote
  module Scheduleservice
    module Tag
      module V1
        CreateTagRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bannote.scheduleservice.tag.v1.CreateTagRequest").msgclass
        GetTagRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bannote.scheduleservice.tag.v1.GetTagRequest").msgclass
        DeleteTagRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bannote.scheduleservice.tag.v1.DeleteTagRequest").msgclass
        DeleteTagResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bannote.scheduleservice.tag.v1.DeleteTagResponse").msgclass
        CreateTagResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bannote.scheduleservice.tag.v1.CreateTagResponse").msgclass
        GetTagResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bannote.scheduleservice.tag.v1.GetTagResponse").msgclass
        GetTagListRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bannote.scheduleservice.tag.v1.GetTagListRequest").msgclass
        GetTagListResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bannote.scheduleservice.tag.v1.GetTagListResponse").msgclass
      end
    end
  end
end
