# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: tag/tag_service.proto for package 'Bannote.Scheduleservice.Tag.V1'

require 'grpc'
require 'tag/tag_service_pb'

module Bannote
  module Scheduleservice
    module Tag
      module V1
        module TagService
          class Service

            include ::GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = 'bannote.scheduleservice.tag.v1.TagService'

            rpc :CreateTag, ::Bannote::Scheduleservice::Tag::V1::CreateTagRequest, ::Bannote::Scheduleservice::Tag::V1::CreateTagResponse
            rpc :GetTag, ::Bannote::Scheduleservice::Tag::V1::GetTagRequest, ::Bannote::Scheduleservice::Tag::V1::GetTagResponse
            rpc :GetTagList, ::Bannote::Scheduleservice::Tag::V1::GetTagListRequest, ::Bannote::Scheduleservice::Tag::V1::GetTagListResponse
            rpc :DeleteTag, ::Bannote::Scheduleservice::Tag::V1::DeleteTagRequest, ::Bannote::Scheduleservice::Tag::V1::DeleteTagResponse
          end

          Stub = Service.rpc_stub_class
        end
      end
    end
  end
end
