# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: room_exception/service.proto for package 'studyroom.room_exception.v1'

require 'grpc'
require 'room_exception/service_pb'

module Studyroom
  module RoomException
    module V1
      module RoomExceptionService
        # RoomException 서비스 정의
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'studyroom.room_exception.v1.RoomExceptionService'

          # 스터디룸 예외 생성
          rpc :CreateRoomException, ::Studyroom::RoomException::V1::CreateRoomExceptionRequest, ::Studyroom::RoomException::V1::CreateRoomExceptionResponse
          # 특정 스터디룸 예외 조회
          rpc :GetRoomException, ::Studyroom::RoomException::V1::GetRoomExceptionRequest, ::Studyroom::RoomException::V1::GetRoomExceptionResponse
          # 스터디룸 예외 목록 조회
          rpc :ListRoomExceptions, ::Studyroom::RoomException::V1::ListRoomExceptionsRequest, ::Studyroom::RoomException::V1::ListRoomExceptionsResponse
          # 스터디룸 예외 정보 업데이트
          rpc :UpdateRoomException, ::Studyroom::RoomException::V1::UpdateRoomExceptionRequest, ::Studyroom::RoomException::V1::UpdateRoomExceptionResponse
          # 스터디룸 예외 삭제 (소프트 삭제)
          rpc :DeleteRoomException, ::Studyroom::RoomException::V1::DeleteRoomExceptionRequest, ::Studyroom::RoomException::V1::DeleteRoomExceptionResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
