# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: room_exception/service.proto

require 'google/protobuf'

require 'room_exception/room_exception_pb'


descriptor_data = "\n\x1croom_exception/service.proto\x12\x1bstudyroom.room_exception.v1\x1a#room_exception/room_exception.proto2\xc0\x05\n\x14RoomExceptionService\x12\x88\x01\n\x13\x43reateRoomException\x12\x37.studyroom.room_exception.v1.CreateRoomExceptionRequest\x1a\x38.studyroom.room_exception.v1.CreateRoomExceptionResponse\x12\x7f\n\x10GetRoomException\x12\x34.studyroom.room_exception.v1.GetRoomExceptionRequest\x1a\x35.studyroom.room_exception.v1.GetRoomExceptionResponse\x12\x85\x01\n\x12ListRoomExceptions\x12\x36.studyroom.room_exception.v1.ListRoomExceptionsRequest\x1a\x37.studyroom.room_exception.v1.ListRoomExceptionsResponse\x12\x88\x01\n\x13UpdateRoomException\x12\x37.studyroom.room_exception.v1.UpdateRoomExceptionRequest\x1a\x38.studyroom.room_exception.v1.UpdateRoomExceptionResponse\x12\x88\x01\n\x13\x44\x65leteRoomException\x12\x37.studyroom.room_exception.v1.DeleteRoomExceptionRequest\x1a\x38.studyroom.room_exception.v1.DeleteRoomExceptionResponseb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Studyroom
  module RoomException
    module V1
    end
  end
end
