# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: schedule_link/schedule_link_service.proto for package 'Bannote.Scheduleservice.ScheduleLink.V1'

require 'grpc'
require 'schedule_link/schedule_link_service_pb'

module Bannote
  module Scheduleservice
    module ScheduleLink
      module V1
        module ScheduleLinkService
          class Service

            include ::GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = 'bannote.scheduleservice.schedule_link.v1.ScheduleLinkService'

            rpc :CreateScheduleLink, ::Bannote::Scheduleservice::ScheduleLink::V1::CreateScheduleLinkRequest, ::Bannote::Scheduleservice::ScheduleLink::V1::CreateScheduleLinkResponse
            rpc :GetScheduleLink, ::Bannote::Scheduleservice::ScheduleLink::V1::GetScheduleLinkRequest, ::Bannote::Scheduleservice::ScheduleLink::V1::GetScheduleLinkResponse
            rpc :UpdateScheduleLink, ::Bannote::Scheduleservice::ScheduleLink::V1::UpdateScheduleLinkRequest, ::Bannote::Scheduleservice::ScheduleLink::V1::UpdateScheduleLinkResponse
            rpc :DeleteScheduleLink, ::Bannote::Scheduleservice::ScheduleLink::V1::DeleteScheduleLinkRequest, ::Bannote::Scheduleservice::ScheduleLink::V1::DeleteScheduleLinkResponse
          end

          Stub = Service.rpc_stub_class
        end
      end
    end
  end
end
