# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schedule_link/schedule_link.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'


descriptor_data = "\n!schedule_link/schedule_link.proto\x12(bannote.scheduleservice.schedule_link.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x98\x04\n\x0cScheduleLink\x12\x17\n\x07link_id\x18\x01 \x01(\x03R\x06linkId\x12\x1f\n\x0bschedule_id\x18\x02 \x01(\x03R\nscheduleId\x12\x14\n\x05title\x18\x03 \x01(\tR\x05title\x12\x1e\n\x08place_id\x18\x04 \x01(\x03H\x00R\x07placeId\x88\x01\x01\x12\"\n\nplace_text\x18\x05 \x01(\tH\x01R\tplaceText\x88\x01\x01\x12 \n\x0b\x64\x65scription\x18\x06 \x01(\tR\x0b\x64\x65scription\x12\x39\n\nstart_time\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\tstartTime\x12\x35\n\x08\x65nd_time\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x07\x65ndTime\x12\x1b\n\tis_allday\x18\t \x01(\x08R\x08isAllday\x12\x1d\n\ncreated_by\x18\n \x01(\x03R\tcreatedBy\x12\x39\n\ncreated_at\x18\x0b \x01(\x0b\x32\x1a.google.protobuf.TimestampR\tcreatedAt\x12>\n\nupdated_at\x18\x0c \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x02R\tupdatedAt\x88\x01\x01\x42\x0b\n\t_place_idB\r\n\x0b_place_textB\r\n\x0b_updated_atB\x80\x02\n,com.bannote.scheduleservice.schedule_link.v1B\x11ScheduleLinkProtoP\x01\xa2\x02\x03\x42SS\xaa\x02\'Bannote.Scheduleservice.ScheduleLink.V1\xca\x02\'Bannote\\Scheduleservice\\ScheduleLink\\V1\xe2\x02\x33\x42\x61nnote\\Scheduleservice\\ScheduleLink\\V1\\GPBMetadata\xea\x02*Bannote::Scheduleservice::ScheduleLink::V1b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Bannote
  module Scheduleservice
    module ScheduleLink
      module V1
        ScheduleLink = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bannote.scheduleservice.schedule_link.v1.ScheduleLink").msgclass
      end
    end
  end
end
