# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: reservation/service.proto for package 'Bannote.Studyroomservice.Reservation.V1'

require 'grpc'
require 'reservation/service_pb'

module Bannote
  module Studyroomservice
    module Reservation
      module V1
        module ReservationService
          # ================================
          # Reservation Service
          # - 스터디룸 예약 생성, 조회, 수정, 삭제를 담당하는 서비스
          # ================================
          # Reservation 서비스 정의
          class Service

            include ::GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = 'bannote.studyroomservice.reservation.v1.ReservationService'

            # 예약 생성
            rpc :CreateReservation, ::Bannote::Studyroomservice::Reservation::V1::CreateReservationRequest, ::Bannote::Studyroomservice::Reservation::V1::CreateReservationResponse
            # 특정 예약 조회
            rpc :GetReservation, ::Bannote::Studyroomservice::Reservation::V1::GetReservationRequest, ::Bannote::Studyroomservice::Reservation::V1::GetReservationResponse
            # 예약 목록 조회
            rpc :ListReservations, ::Bannote::Studyroomservice::Reservation::V1::ListReservationsRequest, ::Bannote::Studyroomservice::Reservation::V1::ListReservationsResponse
            # 예약 정보 업데이트
            rpc :UpdateReservation, ::Bannote::Studyroomservice::Reservation::V1::UpdateReservationRequest, ::Bannote::Studyroomservice::Reservation::V1::UpdateReservationResponse
            # 예약 삭제 (소프트 삭제)
            rpc :DeleteReservation, ::Bannote::Studyroomservice::Reservation::V1::DeleteReservationRequest, ::Bannote::Studyroomservice::Reservation::V1::DeleteReservationResponse
          end

          Stub = Service.rpc_stub_class
        end
      end
    end
  end
end
