# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reservation/service.proto

require 'google/protobuf'

require 'reservation/reservation_pb'


descriptor_data = "\n\x19reservation/service.proto\x12\x18studyroom.reservation.v1\x1a\x1dreservation/reservation.proto2\xfe\x04\n\x12ReservationService\x12|\n\x11\x43reateReservation\x12\x32.studyroom.reservation.v1.CreateReservationRequest\x1a\x33.studyroom.reservation.v1.CreateReservationResponse\x12s\n\x0eGetReservation\x12/.studyroom.reservation.v1.GetReservationRequest\x1a\x30.studyroom.reservation.v1.GetReservationResponse\x12y\n\x10ListReservations\x12\x31.studyroom.reservation.v1.ListReservationsRequest\x1a\x32.studyroom.reservation.v1.ListReservationsResponse\x12|\n\x11UpdateReservation\x12\x32.studyroom.reservation.v1.UpdateReservationRequest\x1a\x33.studyroom.reservation.v1.UpdateReservationResponse\x12|\n\x11\x44\x65leteReservation\x12\x32.studyroom.reservation.v1.DeleteReservationRequest\x1a\x33.studyroom.reservation.v1.DeleteReservationResponseb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Studyroom
  module Reservation
    module V1
    end
  end
end
