# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: reservation/service.proto for package 'studyroom.reservation.v1'

require 'grpc'
require 'reservation/service_pb'

module Studyroom
  module Reservation
    module V1
      module ReservationService
        # Reservation 서비스 정의
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'studyroom.reservation.v1.ReservationService'

          # 예약 생성
          rpc :CreateReservation, ::Studyroom::Reservation::V1::CreateReservationRequest, ::Studyroom::Reservation::V1::CreateReservationResponse
          # 특정 예약 조회
          rpc :GetReservation, ::Studyroom::Reservation::V1::GetReservationRequest, ::Studyroom::Reservation::V1::GetReservationResponse
          # 예약 목록 조회
          rpc :ListReservations, ::Studyroom::Reservation::V1::ListReservationsRequest, ::Studyroom::Reservation::V1::ListReservationsResponse
          # 예약 정보 업데이트
          rpc :UpdateReservation, ::Studyroom::Reservation::V1::UpdateReservationRequest, ::Studyroom::Reservation::V1::UpdateReservationResponse
          # 예약 삭제 (소프트 삭제)
          rpc :DeleteReservation, ::Studyroom::Reservation::V1::DeleteReservationRequest, ::Studyroom::Reservation::V1::DeleteReservationResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
