# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: allowedemail/service.proto for package 'Bannote.Userservice.Allowedemail.V1'

require 'grpc'
require 'allowedemail/service_pb'

module Bannote
  module Userservice
    module Allowedemail
      module V1
        module AllowedEmailService
          # Gateway에서 gRPC metadata로 전달되는 정보:
          # - user-id: 요청하는 유저의 ID
          # - user-role: 요청하는 유저의 역할 (ADMIN, STUDENT, EMPLOYEE 등)
          #
          # The email allowlist service definition.
          class Service

            include ::GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = 'bannote.userservice.allowedemail.v1.AllowedEmailService'

            #  이메일 허용 목록 추가 API
            rpc :AddAllowedEmail, ::Bannote::Userservice::Allowedemail::V1::AddAllowedEmailRequest, ::Bannote::Userservice::Allowedemail::V1::AddAllowedEmailResponse
            #  이메일 허용 목록 삭제 API
            rpc :RemoveAllowedEmail, ::Bannote::Userservice::Allowedemail::V1::RemoveAllowedEmailRequest, ::Bannote::Userservice::Allowedemail::V1::RemoveAllowedEmailResponse
            #  이메일 허용 목록 전체 조회 API
            rpc :ListAllowedEmail, ::Bannote::Userservice::Allowedemail::V1::ListAllowedEmailRequest, ::Bannote::Userservice::Allowedemail::V1::ListAllowedEmailResponse
          end

          Stub = Service.rpc_stub_class
        end
      end
    end
  end
end
