# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: allowedemail/service.proto

require 'google/protobuf'

require 'allowedemail/allowedemail_pb'


descriptor_data = "\n\x1a\x61llowedemail/service.proto\x12#bannote.userservice.allowedemail.v1\x1a\x1f\x61llowedemail/allowedemail.proto\".\n\x16\x41\x64\x64\x41llowedEmailRequest\x12\x14\n\x05\x65mail\x18\x01 \x01(\tR\x05\x65mail\"q\n\x17\x41\x64\x64\x41llowedEmailResponse\x12V\n\rallowed_email\x18\x01 \x01(\x0b\x32\x31.bannote.userservice.allowedemail.v1.AllowedEmailR\x0c\x61llowedEmail\"1\n\x19RemoveAllowedEmailRequest\x12\x14\n\x05\x65mail\x18\x01 \x01(\tR\x05\x65mail\"t\n\x1aRemoveAllowedEmailResponse\x12V\n\rallowed_email\x18\x01 \x01(\x0b\x32\x31.bannote.userservice.allowedemail.v1.AllowedEmailR\x0c\x61llowedEmail\"A\n\x17ListAllowedEmailRequest\x12\x12\n\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n\x04size\x18\x02 \x01(\x05R\x04size\"\xbb\x01\n\x18ListAllowedEmailResponse\x12V\n\rallowed_email\x18\x01 \x03(\x0b\x32\x31.bannote.userservice.allowedemail.v1.AllowedEmailR\x0c\x61llowedEmail\x12\x1f\n\x0btotal_count\x18\x02 \x01(\x05R\ntotalCount\x12\x12\n\x04page\x18\x03 \x01(\x05R\x04page\x12\x12\n\x04size\x18\x04 \x01(\x05R\x04size2\xd4\x03\n\x13\x41llowedEmailService\x12\x8e\x01\n\x0f\x41\x64\x64\x41llowedEmail\x12;.bannote.userservice.allowedemail.v1.AddAllowedEmailRequest\x1a<.bannote.userservice.allowedemail.v1.AddAllowedEmailResponse\"\x00\x12\x97\x01\n\x12RemoveAllowedEmail\x12>.bannote.userservice.allowedemail.v1.RemoveAllowedEmailRequest\x1a?.bannote.userservice.allowedemail.v1.RemoveAllowedEmailResponse\"\x00\x12\x91\x01\n\x10ListAllowedEmail\x12<.bannote.userservice.allowedemail.v1.ListAllowedEmailRequest\x1a=.bannote.userservice.allowedemail.v1.ListAllowedEmailResponse\"\x00\x42\xb0\x02\n\'com.bannote.userservice.allowedemail.v1B\x0cServiceProtoP\x01ZHgithub.com/kyumin1227/bannote-proto/gen/go/user-service/allowed_email/v1\xa2\x02\x03\x42UA\xaa\x02#Bannote.Userservice.Allowedemail.V1\xca\x02#Bannote\\Userservice\\Allowedemail\\V1\xe2\x02/Bannote\\Userservice\\Allowedemail\\V1\\GPBMetadata\xea\x02&Bannote::Userservice::Allowedemail::V1b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Bannote
  module Userservice
    module Allowedemail
      module V1
        AddAllowedEmailRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bannote.userservice.allowedemail.v1.AddAllowedEmailRequest").msgclass
        AddAllowedEmailResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bannote.userservice.allowedemail.v1.AddAllowedEmailResponse").msgclass
        RemoveAllowedEmailRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bannote.userservice.allowedemail.v1.RemoveAllowedEmailRequest").msgclass
        RemoveAllowedEmailResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bannote.userservice.allowedemail.v1.RemoveAllowedEmailResponse").msgclass
        ListAllowedEmailRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bannote.userservice.allowedemail.v1.ListAllowedEmailRequest").msgclass
        ListAllowedEmailResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bannote.userservice.allowedemail.v1.ListAllowedEmailResponse").msgclass
      end
    end
  end
end
