# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: token/token.proto

require 'google/protobuf'


descriptor_data = "\n\x11token/token.proto\x12\x1d\x62\x61nnote.tokenservice.token.v1\"K\n\x1aGenerateAccessTokenRequest\x12\x17\n\x07user_id\x18\x01 \x01(\tR\x06userId\x12\x14\n\x05roles\x18\x02 \x01(\tR\x05roles\"_\n\x1bGenerateAccessTokenResponse\x12!\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\tR\x0b\x61\x63\x63\x65ssToken\x12\x1d\n\nexpires_at\x18\x02 \x01(\x03R\texpiresAt\"?\n\x1aValidateAccessTokenRequest\x12!\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\tR\x0b\x61\x63\x63\x65ssToken\"x\n\x1bValidateAccessTokenResponse\x12\x14\n\x05valid\x18\x01 \x01(\x08R\x05valid\x12\x17\n\x07user_id\x18\x02 \x01(\tR\x06userId\x12\x14\n\x05roles\x18\x03 \x01(\tR\x05roles\x12\x14\n\x05\x65rror\x18\x04 \x01(\tR\x05\x65rror2\xac\x02\n\x0cTokenService\x12\x8c\x01\n\x13GenerateAccessToken\x12\x39.bannote.tokenservice.token.v1.GenerateAccessTokenRequest\x1a:.bannote.tokenservice.token.v1.GenerateAccessTokenResponse\x12\x8c\x01\n\x13ValidateAccessToken\x12\x39.bannote.tokenservice.token.v1.ValidateAccessTokenRequest\x1a:.bannote.tokenservice.token.v1.ValidateAccessTokenResponseB\xc6\x01\n!com.bannote.tokenservice.token.v1B\nTokenProtoP\x01\xa2\x02\x03\x42TT\xaa\x02\x1d\x42\x61nnote.Tokenservice.Token.V1\xca\x02\x1d\x42\x61nnote\\Tokenservice\\Token\\V1\xe2\x02)Bannote\\Tokenservice\\Token\\V1\\GPBMetadata\xea\x02 Bannote::Tokenservice::Token::V1b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Bannote
  module Tokenservice
    module Token
      module V1
        GenerateAccessTokenRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bannote.tokenservice.token.v1.GenerateAccessTokenRequest").msgclass
        GenerateAccessTokenResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bannote.tokenservice.token.v1.GenerateAccessTokenResponse").msgclass
        ValidateAccessTokenRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bannote.tokenservice.token.v1.ValidateAccessTokenRequest").msgclass
        ValidateAccessTokenResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bannote.tokenservice.token.v1.ValidateAccessTokenResponse").msgclass
      end
    end
  end
end
