# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: token/token.proto for package 'Bannote.Tokenservice.Token.V1'

require 'grpc'
require 'token/token_pb'

module Bannote
  module Tokenservice
    module Token
      module V1
        module TokenService
          class Service

            include ::GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = 'bannote.tokenservice.token.v1.TokenService'

            rpc :GenerateAccessToken, ::Bannote::Tokenservice::Token::V1::GenerateAccessTokenRequest, ::Bannote::Tokenservice::Token::V1::GenerateAccessTokenResponse
            rpc :ValidateAccessToken, ::Bannote::Tokenservice::Token::V1::ValidateAccessTokenRequest, ::Bannote::Tokenservice::Token::V1::ValidateAccessTokenResponse
          end

          Stub = Service.rpc_stub_class
        end
      end
    end
  end
end
